### ISSUE TITLE
Currently not working with cljs and advanced compilation

### ISSUE THREAD

**Issue by JustinC474** [circleci/bond#20]
This bug - http://dev.clojure.org/jira/browse/CLJS-1623 - keeps the bond library from working with advanced compilation on.

**Comment by neeasade** [comment]
Closing due to dropped support for cljs -- see #53 for details (tl;dr cljs needs runtime calls for `ns-publics` now, and `ns-fn-symbols` where `ns-publics` is used is a macro)
