### ISSUE TITLE
Trouble compiling when requiring bond in cljs test ns

### ISSUE THREAD

**Issue by akombo** [circleci/bond#48]
When requiring and compiling I receive the following exception:
...
Caused by: clojure.lang.ExceptionInfo: Assert failed: Argument to ns-publics must be a quoted symbol
(core/and (seq? quoted-ns) (= (first quoted-ns) (quote quote)) (core/symbol? (second quoted-ns))) at line 34 target/out/bond/james.cljc {:file "target/out/bond/james.cljc", :line 34, :column 8, :tag :cljs/analysis-error}
...

Building a local version of bond with a change to line 34 in ns->fn-symbols fixes the problem:
Change (ns-publics ns) to (ns-publics (quote ns)).

I'm relatively new to cljs so am not sure if something else, like project.clj config, is my actual problem. Also, I'm guessing the changed line would need to check for the existence of a quote before quoting if this were to prevent creating new problems.

Thanks

**Comment by neeasade** [comment]
Closing due to dropped support for cljs -- see https://github.com/circleci/bond/pull/53 for details (tl;dr cljs needs runtime calls for `ns-publics` now, and `ns->fn-symbols` where `ns-publics is used is a macro)
